"use client";

import { useState } from "react";
import { getPreferences, getTodayUsage, loadSessionKey, recordUsage } from "@/lib/client-store";

function formatDate(value) {
  return value ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "—";
}

export default function ResearchIntelligence({ research, onResearch, onNeedKey, onGenerate }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [tab, setTab] = useState("overview");
  async function refresh() {
    const preferences = getPreferences(); const usage = getTodayUsage();
    if (usage.research >= preferences.dailyResearchLimit) { setError(`Daily Deep Search limit reached (${preferences.dailyResearchLimit}). Adjust it in Settings if needed.`); return; }
    setBusy(true); setError("");
    try {
      const key = loadSessionKey(); const response = await fetch("/api/research", { method: "POST", headers: { "Content-Type": "application/json", ...(key ? { "x-openai-key": key } : {}) }, body: "{}" });
      const data = await response.json(); if (!response.ok) { const problem = new Error(data.error); problem.status = response.status; throw problem; }
      onResearch(data.research); recordUsage("research", 1);
    } catch (problem) { setError(problem.message); if (problem.status === 401) onNeedKey(); }
    finally { setBusy(false); }
  }
  return <section className="intelligence-page"><div className="page-title"><div><span className="overline">DEEP SEARCH · INDIA LENS</span><h1>Pattern intelligence, <em>with receipts.</em></h1><p>Twenty-year context, current disease signals and calibrated forecasts—not leaked-question theatre.</p></div><button className="primary-button" onClick={refresh} disabled={busy}>{busy ? <><span className="spinner" /> Searching the evidence…</> : `⌁ ${research ? "Refresh intelligence" : "Run Deep Search"}`}</button></div>{error && <div className="error-banner">{error}</div>}
    {research ? <><div className="intel-hero"><div className="intel-pulse"><span /><i /><b>LIVE</b></div><div><span className="overline light-overline">UPDATED {formatDate(research.generatedAt)} · {research.sources?.length || 0} SOURCES</span><h2>{research.headline}</h2><p>{research.summary}</p></div><button className="light-button" onClick={onGenerate}>Generate from this map →</button></div>
      <div className="intel-tabs">{[["overview", "Exam map"], ["history", "20-year lens"], ["forecast", "Forecast"], ["disease", "Disease watch"]].map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}{id === "disease" && <i />}</button>)}</div>
      {tab === "overview" && <div className="intel-overview"><div className="panel intel-signals"><div className="panel-head"><div><span className="overline">REASONING SIGNALS</span><h3>What setters increasingly ask you to do</h3></div></div><ol>{(research.examSignals || []).map((signal, index) => <li key={signal}><span>{String(index + 1).padStart(2, "0")}</span><p>{signal}</p></li>)}</ol></div><div className="panel guideline-panel"><div className="panel-head"><div><span className="overline">GUIDELINE WATCH</span><h3>Verify before testing</h3></div></div>{(research.guidelineWatch || []).map((item) => <p key={item}><span>!</span>{item}</p>)}</div><div className="panel topic-panel intel-topic"><div className="panel-head"><div><span className="overline">HIGH-YIELD QUEUE</span><h3>Topic families worth reasoning through</h3></div><span className="tiny-badge">Not official weightage</span></div><div className="topic-cloud">{(research.highYieldTopics || []).map((item) => <article key={`${item.subject}-${item.topic}`}><span>{item.subject}</span><b>{item.topic}</b><p>{item.rationale}</p><i>{item.priority}</i></article>)}</div></div></div>}
      {tab === "history" && <div className="history-layout"><div className="panel history-timeline"><div className="panel-head"><div><span className="overline">EVOLUTION, NOT A QUESTION BANK</span><h3>How postgraduate entrance reasoning changed</h3></div></div>{(research.historicalPatterns || []).map((item, index) => <div className="history-event" key={`${item.era}-${index}`}><span>{item.era}</span><i /><p><b>{item.shift}</b><small className={`evidence-chip ${item.evidenceType.replace(" ", "-").toLowerCase()}`}>{item.evidenceType}</small></p></div>)}</div><aside className="method-card"><span>METHOD NOTE</span><p>{research.methodologyNote}</p><div><b>Official</b>Exam-body rules, archives or notices.</div><div><b>Recall signal</b>Repeated but non-official candidate/educator reports.</div><div><b>Inference</b>AI synthesis; useful direction, not fact.</div></aside></div>}
      {tab === "forecast" && <div className="forecast-grid">{["Next exam", "1–3 years", "3–10 years"].map((horizon) => <section className="forecast-column" key={horizon}><div><span>{horizon === "Next exam" ? "NOW" : horizon}</span><h3>{horizon}</h3></div>{(research.forecastTopics || []).filter((item) => item.horizon === horizon).map((item) => <article key={item.topic}><span className={`confidence ${item.confidence.toLowerCase()}`}>{item.confidence} confidence</span><b>{item.topic}</b><p>{item.rationale}</p></article>)}</section>)}</div>}
      {tab === "disease" && <div className="disease-grid">{(research.diseaseWatch || []).map((item) => <article key={`${item.disease}-${item.geography}`}><div className="disease-top"><span className={`disease-status ${item.status.replace(" ", "-").toLowerCase()}`}><i />{item.status}</span><small>{item.geography}</small></div><h3>{item.disease}</h3><p>{item.signal}</p><div><span>EXAM ANGLE</span>{item.examAngle}</div></article>)}</div>}
      <div className="source-panel intel-sources"><span className="overline">SEARCH SOURCES</span><div>{research.sources?.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.title} ↗</a>)}</div><p>Web signals can change. Every generated medical explanation remains educational and should be checked against current authoritative guidance.</p></div>
    </> : <div className="research-empty intel-empty"><div className="research-rings"><span>⌁</span></div><span className="overline">NO INTELLIGENCE BRIEF YET</span><h2>Search broadly. Believe selectively.</h2><p>Deep Search separates official facts from recall signals and inference, scans India-relevant disease sources, and builds confidence-labelled forecasts for question families—not exact questions.</p><div className="source-badges"><span>NBEMS</span><span>AIIMS</span><span>WHO</span><span>ICMR</span><span>NCDC</span><span>MoHFW</span></div><button className="primary-button" onClick={refresh}>Run India-focused Deep Search</button></div>}
  </section>;
}
