"use client";

import { useEffect, useState } from "react";
import { getPreferences, getTodayUsage, loadSessionKey, savePreferences, saveSessionKey } from "@/lib/client-store";

export default function SettingsPanel({ onClose, onSaved }) {
  const [key, setKey] = useState(loadSessionKey()); const [show, setShow] = useState(false); const [health, setHealth] = useState(null);
  const [preferences, setPreferences] = useState(getPreferences()); const usage = getTodayUsage();
  useEffect(() => { fetch("/api/health").then((response) => response.json()).then(setHealth).catch(() => {}); }, []);
  const runtime = health?.config;
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal settings-v2"><div className="modal-head"><div><span className="overline">CONTROL ROOM</span><h2>API & generation limits</h2></div><button className="icon-button" onClick={onClose} aria-label="Close settings">×</button></div>
    <div className="key-illustration"><span>⌁</span><div><b>Bring your own OpenAI key</b><p>The key is kept only in this browser tab and sent to same-origin server routes. It is never saved with questions, reports or Supabase records.</p></div></div>
    <label className="field-label" htmlFor="api-key-v2">OpenAI API key</label><div className="key-input"><input id="api-key-v2" type={show ? "text" : "password"} value={key} onChange={(event) => setKey(event.target.value)} placeholder="sk-…" autoComplete="off" /><button onClick={() => setShow(!show)}>{show ? "Hide" : "Show"}</button></div><p className="field-help">Leave blank to use <code>OPENAI_API_KEY</code> from the deployed server. Deep Search uses the Responses API web-search tool—no separate Google key is required.</p>
    <div className="config-banner"><div><span className="overline">ONE PLACE TO CONFIGURE</span><b>Local secrets live in <code>.env.local</code>. Production secrets live in Vercel Environment Variables.</b><p>Never put real secrets inside <code>NEXT_PUBLIC_*</code>. Those values are exposed to the browser bundle by design.</p></div><span className="config-badge">{health?.appUrl || "http://localhost:3000"}</span></div>
    <div className="config-board">
      <article className="config-card"><span className="overline">SERVER RUNTIME</span><h3>Current AI runtime</h3><div className="config-list"><div><span>Model</span><code>{runtime?.openai?.model || "Set OPENAI_MODEL"}</code></div><div><span>Question speed</span><b>{runtime?.openai?.generationEffort || "medium"} effort · {runtime?.openai?.searchContextSize || "medium"} search</b></div><div><span>Research speed</span><b>{runtime?.openai?.researchEffort || "medium"} effort · {runtime?.openai?.researchSearchContextSize || "medium"} search</b></div><div><span>Key priority</span><b>{key ? "Session key overrides server key" : "Server key first if configured"}</b></div></div></article>
      <article className="config-card"><span className="overline">OPTIONAL STORAGE</span><h3>Cloud sync status</h3><div className="config-list"><div><span>Candidate history</span><b>{health?.supabaseConfigured ? "Synced with Supabase" : "Stored only on this device"}</b></div><div><span>Anon browser key</span><b>{runtime?.supabase?.configured ? "Configured" : "Not configured"}</b></div><div><span>Research snapshots</span><b>{runtime?.supabase?.researchSyncEnabled ? "Saved on the server" : "In-memory unless Supabase service role is added"}</b></div><div><span>Cron protection</span><b>{runtime?.cron?.configured ? "CRON_SECRET set" : "Disabled until CRON_SECRET is added"}</b></div></div></article>
      <article className="config-card accent"><span className="overline">FAST START</span><h3>Keep the app snappy</h3><div className="config-points"><p><b>Server-side key:</b> Best for speed and security because the browser skips repeated key entry.</p><p><b>Use medium effort:</b> The default runtime now targets lower latency for daily generation and research.</p><p><b>Disable Deep Search:</b> Fastest paper builds come from turning research off for routine practice sets.</p></div></article>
    </div>
    <div className="settings-grid"><label><span>Daily question ceiling</span><select value={preferences.dailyQuestionLimit} onChange={(event) => setPreferences({ ...preferences, dailyQuestionLimit: Number(event.target.value) })}><option value="50">50 questions</option><option value="180">180 questions</option><option value="360">360 questions</option><option value="720">720 questions</option></select><small>Local cost guard; resets each day.</small></label><label><span>Deep searches per day</span><select value={preferences.dailyResearchLimit} onChange={(event) => setPreferences({ ...preferences, dailyResearchLimit: Number(event.target.value) })}><option value="1">1 search</option><option value="3">3 searches</option><option value="5">5 searches</option><option value="10">10 searches</option></select><small>Includes related-question research.</small></label></div>
    <label className="adaptive-setting"><input type="checkbox" checked={preferences.adaptiveMode} onChange={(event) => setPreferences({ ...preferences, adaptiveMode: event.target.checked })} /><span><b>Adaptive learning by default</b><small>Uses only your generated-question history to choose focus and difficulty.</small></span></label>
    <div className="usage-meter"><div><span>TODAY’S LOCAL LIMIT</span><b>{usage.questions}/{preferences.dailyQuestionLimit} questions · {usage.research}/{preferences.dailyResearchLimit} searches</b></div><i><b style={{ width: `${Math.min(100, usage.questions / preferences.dailyQuestionLimit * 100)}%` }} /></i></div>
    <div className="connection-status"><span className={health?.openaiConfigured ? "online" : ""}><i /> Server key {health?.openaiConfigured ? "configured" : "not configured"}</span><span className={health?.supabaseConfigured ? "online" : ""}><i /> Storage: {health?.supabaseConfigured ? "Supabase" : "private device"}</span></div>
    <div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => { saveSessionKey(key); savePreferences(preferences); onSaved(); }}>Save controls</button></div>
  </div></div>;
}
